######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : image_resize_wf, Index = 0, Count = null
# SUBMIT FILE NAME : create_dir_image_resize_wf_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=346f40d3-ec92-49c1-ace1-c193fc9c03e7 PEGASUS_WF_LABEL=image_resize_wf PEGASUS_DAG_JOB_ID=create_dir_image_resize_wf_0_local PEGASUS_SITE=local"
arguments = " -n pegasus::dirmanager -N null -i - -R local  -L image_resize_wf -T 2020-08-15T01:11:51+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-transfer "
error = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0001//00/00/create_dir_image_resize_wf_0_local.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
input = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0001//00/00/create_dir_image_resize_wf_0_local.in
log = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0001/image_resize_wf-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0001//00/00/create_dir_image_resize_wf_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "346f40d3-ec92-49c1-ace1-c193fc9c03e7"
+pegasus_wf_uuid = "346f40d3-ec92-49c1-ace1-c193fc9c03e7"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "image_resize_wf-0"
+pegasus_wf_time = "20200815T011153+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_image_resize_wf_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
