######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : image_resize_wf, Index = 0, Count = null
# SUBMIT FILE NAME : image_resize_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=da43fb82-f4b8-4278-8cb7-4fa04ce14c5e PEGASUS_WF_LABEL=image_resize_wf PEGASUS_DAG_JOB_ID=image_resize_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003//00/00/image_resize_ID0000001.err
executable = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003/00/00/image_resize_ID0000001.sh
initialdir = /home/scitech/shared-data/sample-images-wf/wf-scratch/LOCAL/scitech/pegasus/image_resize_wf/run0003
log = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003/image_resize_wf-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003//00/00/image_resize_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = img3.jpeg,img1.jpeg,image_resize,img2.jpeg,img.jpeg,/home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/sample-images-wf/scitech/pegasus/image_resize_wf/run0003/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = image_2.jpeg,image_3.jpeg,image_0.jpeg,image_1.jpeg
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "da43fb82-f4b8-4278-8cb7-4fa04ce14c5e"
+pegasus_wf_uuid = "da43fb82-f4b8-4278-8cb7-4fa04ce14c5e"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "image_resize_wf-0"
+pegasus_wf_time = "20200815T012602+0000"
+pegasus_wf_xformation = "image_resize"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "image_resize_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
